paste/routes.py
import re

import magic
from werkzeug.exceptions import NotFound
from quart import render_template, request, redirect, url_for, jsonify, Blueprint, abort

from paste.utils import sanitize_expiration
from paste.paste import Pastes

bp_routes = Blueprint('routes', __name__)


@bp_routes.route('/')
async def index():
    return await render_template("index.html")


@bp_routes.route("/<any(p, a, i):_type>/<path:uid>")
@bp_routes.route("/<any(p, a, i):_type>/<path:uid>.<path:extension>")
async def paste_view(_type, uid: str, extension=None):
    if not len(uid) == 5:
        return abort(500)

    if _type == "p":
        paste = await Pastes.read_plain_uid(uid)
        if not paste:
            return abort(404, "No such paste.")
        if extension:
            return paste["content"], {
                'Content-Type': 'text/plain',
                'Cache-Control': 'no-cache'
            }
        return await render_template("paste.html", _type=_type, paste=paste)
    elif _type == "a":
        album = await Pastes.read_album_uid(uid)
        if not album:
            return abort(404, "Album not found.")
        return await render_template("album.html", _type=_type, album=album)
    elif _type == "i":
        image = await Pastes.read_image_uid(uid)
        if not image:
            return abort(404, "Image not found.")
        return image, {
            "Content-Type": magic.from_buffer(image, mime=True),
            "Content-Disposition": f"inline; filename={str(uid)}.png"
        }


@bp_routes.route("/paste/plain", methods=["POST"])
async def paste_plain():
    content = await request.form
    body = content.get("paste[body]", "").encode()
    lang = re.sub("[^0-9a-zA-Z]+", "", content.get("paste[lang]", "plain"))
    expiration = sanitize_expiration(content.get("paste[expir]", 0))

    if not body:
        return abort(422, "incomprehensible content")

    uid = await Pastes.write_plain(
        syntax=lang,
        expiration=expiration,
        contents=body)
    return redirect(url_for("routes.paste_view", _type="p", uid=uid, extension="txt"))


@bp_routes.route("/paste/img", methods=["POST"])
async def paste_img():
    allowed_extensions = [".png", ".jpg", ".gif", ".webm"]
    expiration = sanitize_expiration(request.args.get("expiration", 86400))

    files = await request.files
    files = files.getlist("files[]")
    if not files:
        return abort(400, "no content")

    images = []
    for file in files:
        for ext in allowed_extensions:
            if not file.filename.endswith(ext):
                continue
            images.append(file.read())

    if not images:
        return abort(400, "no content")

    album_uid = await Pastes.write_album(images, expiration)
    images = await Pastes.read_album_uid(album_uid)
    if not images:
        return abort(400, "no content")

    if len(images) > 1:
        url = url_for("routes.paste_view", _type="a", uid=album_uid)
    else:
        url = url_for("routes.paste_view", _type="i", uid=images[0]['uid'], extension=images[0]['extension'])

    return jsonify({
        "success": True,
        "redirect": url
    })


@bp_routes.errorhandler(404)
@bp_routes.errorhandler(500)
async def error(e):
    msg = str(e)
    if isinstance(e, NotFound):
        if e.description:
            msg = f"{msg} - {e.description}"

    return await render_template("error.html", message=msg)


@bp_routes.route("/favicon.ico")
async def favicon():
    return "ok", 200

paste/templates/album.html
{% extends "base.html" %}
{% block content %}

<!--main-->
<div class="container" id="main">
  {% for image in album %}
    {% set url_raw = url_for("routes.paste_view", _type="i", uid=image['uid'], extension=image['extension']) %}
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <div class="panel panel-default">
          <div class="panel-body paste-body">
              <div class="imgg">
                <a href="{{ url_raw }}" target="_blank">
                  <img src="{{url_raw}}"/>
                </a>
              </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
    <div class="clearfix"></div>

    {% include 'footer.html' %}

  <!--/main-->
  {% endblock %}

paste/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Paste</title>

  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/default.min.css">

  <link href="/static/css/paste.css" rel="stylesheet">
  <link href="/static/css/dracula.css" rel="stylesheet">
  <script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/highlight.min.js"></script>

</head>

<body>
{% for message in errors %}
<div class="alert alert-danger">
  <strong>Warning!</strong> {{ message }}
</div>
{% endfor %}

{% block content %} {% endblock %}
</body>
</html>

paste/templates/error.html
{% extends "base.html" %}
{% block content %}

<!--main-->
<div class="container" id="main">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="panel panel-default">
        <div class="panel-body paste-body">
          <p>{{message}}</p>
          <br>
          <p>
            <a href="{{url_for('routes.index')}}">Go back to the main page</a>
          </p>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    {% include 'footer.html' %}

  </div>
  <!--/main-->
  {% endblock %}

paste/templates/header.html
<div class="col-md-7">
    <a href="/">
        <img style="margin-bottom:8px;" src="/static/img/header.png"/>
    </a>
</div>

paste/templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="container" id="main">
  <div class="row">
    <div class="col-md-9 col-sm-9">
      <div class="panel panel-default">
        <div class="panel-body">

          <form accept-charset="UTF-8" action="/paste/plain" class="new_paste" enctype="multipart/form-data" id="editor"
                method="post">

            <div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"></div>

            <div class="chooseLanguage">
              <label>Language:</label>
              <select id="lang" name="paste[lang]" onchange="">
                <option value="plain" selected="selected">Plain text</option>
                <option value="python">Python</option>
                <option value="bash">Bash (shell)</option>
                <option value="javascript">Javascript</option>
                <option value="css">CSS</option>
                <option value="sql">SQL</option>
                <option value="go">Go</option>
                <option value="cpp">C/C++</option>
                <option value="xml">XML</option>
                <option value="markdown">Markdown</option>
                <option value="diff">Diff</option>
                <option value="objectivec">Objective-C/C++</option>
                <option value="php">PHP</option>
                <option value="nginx">Nginx (webserver)</option>
                <option value="actionscript">ActionScript</option>
                <option value="applescript">Applescript</option>
                <option value="arduino">Arduino</option>
                <option value="apache">Apache (webserver)</option>
                <option value="basic">Basic</option>
                <option value="cs">C#</option>
                <option value="coffeescript">CoffeeScript</option>
                <option value="django">Django</option>
                <option value="fortran">Fortran</option>
                <option value="haskell">Haskell</option>
                <option value="html">HTML (ERB / Rails)</option>
                <option value="lua">Lua</option>
                <option value="java">Java</option>
                <option value="perl">Perl</option>
                <option value="puppet">Puppet</option>
                <option value="ruby">Ruby</option>
                <option value="yaml">YAML</option>
              </select>
            </div>

            <div class="chooseExpiration">
              <label>Expiration:</label>
              <select id="expir" name="paste[expir]" onchange="">
                <option value="86400" selected="selected">1 day</option>
                <option value="3600">1 hour</option>
                <option value="600">10 minutes</option>
                <option value="604800">1 week</option>
                <option value="2419200">1 month</option>
              </select>
            </div>

            <p class="legend" id="legend">
              quart-pastebin
            </p>

            <p style="margin-top:20px;">
              <textarea class="pastebox" cols="40" style="width: 100%;" id="paste_body" name="paste[body]" rows="22" tabindex="20"></textarea>
            </p>

            <p class="public" id="public">
              <img alt="Network" height="32" src="/static/img/globe.png" width="32">

              <strong style="margin-left: 4px;" id="exposure">Pastes are private by default.</strong>
            </p>

            <div class="submit" style="margin-bottom:0;">
            <span class="locker">
            <label>
                <img alt="Object-locked" height="24" src="/static/img/locked.png" title="priv8" width="24">
            </label>
            </span>
              <input name="commit" tabindex="30" type="submit" value="Create Paste">
            </div>
            <div style="clear:both"></div>
          </form>

        </div>
      </div>
    </div>

    {% include 'sidebar.html' %}

    <br>
    <div class="clearfix"></div>

    {% include 'footer.html' %}

  </div>

  {% endblock %}

paste/templates/paste.html
{% extends "base.html" %}
{% block content %}

<script>
  hljs.initHighlightingOnLoad();
</script>

{% set url_raw = url_for("routes.paste_view", _type=_type, uid=paste['uid'], extension=paste['extension']) %}
{% set content = paste['content'] %}
{% set syntax = paste['syntax'] %}

<!--main-->
<div class="container" id="main">
  <div class="row">
    <div class="col-md-12">
      <a href="/">back to home</a>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="panel panel-default">
        <div class="panel-body paste-body">
          <p>
            <a style="display: block; float: right;margin-right: 10px;" href="{{ url_raw }}" class="subtle">Raw</a>
          </p>
          <pre><code class="{{ syntax }}">{{ content }}</code></pre>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    {% include 'footer.html' %}

  </div>
  <!--/main-->
  {% endblock %}

paste/templates/sidebar.html
<div class="col-md-3 col-sm-3" id="recent">
  <div class="panel panel-default">
    <div class="panel-body">
      <form method="post" action="/paste/img" enctype="multipart/form-data" novalidate class="box">
        <div class="box__input">
          <input type="file" name="files[]" id="file" class="box__file" data-multiple-caption="{count} files selected" multiple/>

          <div id="dashed_stuff">
            <label for="file">
              <center>
                <div id="img_thingy" style="width:200px;padding-top: 0px;">
                  Upload Image(s) (drag/click)
                  <br>
                  <img style="opacity: 0.4;" width="20px" src="/static/img/down.png"/>
                </div>
              </center>
            </label>
          </div>
          <button type="submit" class="box__button">Upload</button>
        </div>
        <div class="box__uploading">Uploading&hellip;</div>
        <div class="box__success">Done! <a href="#" class="box__restart" role="button">Upload more?</a></div>
        <div class="box__error">Error!</div>
      </form>
    </div>
  </div>
</div>

<script>(function (e, t, n) {
    var r = e.querySelectorAll("html")[0];
    r.className = r.className.replace(/(^|\s)no-js(\s|$)/, "$1js$2")
})(document, window, 0);</script>

<script src="/static/js/image.js"></script>